"""Re-exports for capacity descriptors and ConditionsDescriptor fragments."""

from .medium_equip_penalty import (
    MEDIUM_EQUIP_PENALTY_CAPACITY,
    MEDIUM_EQUIP_PENALTY_CONDITIONS,
    MEDIUM_EQUIP_PENALTY_SF_CAPACITY,
)
from .choc import (
    CHOC_CONDITIONS,
    CHOC_INRANGE_CAPACITY,
    CHOC_INRANGE_FEEDBACK_CAPACITY,
)
from .cmd import CMD_UNIT_CAPACITY
from .deploy import DEPLOY_CAPACITY, DEPLOY_CONDITIONS, DEPLOY_OK_CAPACITY
from .ldr import LDR_ARTY_CAPACITY, LDR_INF_CAPACITY, LDR_TNK_CAPACITY
from .reload_penalty import RELOAD_PENALTY_CAPACITY
from .sprint import SPRINT_CAPACITY, SPRINT_CONDITIONS
from .swift import NO_SWIFT_CAPACITY, SWIFT_CAPACITY, SWIFT_CONDITIONS

CONDITIONS = [
    *SPRINT_CONDITIONS,
    *SWIFT_CONDITIONS,
    *DEPLOY_CONDITIONS,
    *CHOC_CONDITIONS,
    *MEDIUM_EQUIP_PENALTY_CONDITIONS,
]

__all__ = [
    "SPRINT_CAPACITY",
    "SPRINT_CONDITIONS",
    "CONDITIONS",
    "CHOC_INRANGE_CAPACITY",
    "CHOC_INRANGE_FEEDBACK_CAPACITY",
    "CHOC_CONDITIONS",
    "CMD_UNIT_CAPACITY",
    "DEPLOY_CAPACITY",
    "DEPLOY_CONDITIONS",
    "DEPLOY_OK_CAPACITY",
    "LDR_ARTY_CAPACITY",
    "LDR_INF_CAPACITY",
    "LDR_TNK_CAPACITY",
    "MEDIUM_EQUIP_PENALTY_CAPACITY",
    "MEDIUM_EQUIP_PENALTY_CONDITIONS",
    "MEDIUM_EQUIP_PENALTY_SF_CAPACITY",
    "NO_CHOC_MOVE_CAPACITY",
    "NO_SWIFT_CAPACITY",
    "RELOAD_PENALTY_CAPACITY",
    "SWIFT_CAPACITY",
    "SWIFT_CONDITIONS",
]
