"""Re-exports for capacity descriptors and ConditionsDescriptor fragments."""

from .medium_equip_penalty import MEDIUM_EQUIP_PENALTY_CAPACITY
from .deploy import DEPLOY_CAPACITY, DEPLOY_CONDITIONS, DEPLOY_OK_CAPACITY
from .ldr import LDR_ARTY_CAPACITY, LDR_TNK_CAPACITY
from .sprint import (
    NO_SPRINT_CAPACITY,
    SPRINT_CAPACITY,
    SPRINT_ACTIVATED_CAPACITY,
    SPRINT_BEGIN_COOLDOWN_CAPACITY,
    SPRINT_OK_CAPACITY,
    SPRINT_CONDITIONS,
)
from .swift import NO_SWIFT_CAPACITY, SWIFT_CAPACITY, SWIFT_CONDITIONS

CONDITIONS = [
    *SPRINT_CONDITIONS,
    *SWIFT_CONDITIONS,
    *DEPLOY_CONDITIONS,
]

__all__ = [
    "NO_SPRINT_CAPACITY",
    "SPRINT_CAPACITY",
    "SPRINT_ACTIVATED_CAPACITY",
    "SPRINT_BEGIN_COOLDOWN_CAPACITY",
    "SPRINT_OK_CAPACITY",
    "CONDITIONS",
    "DEPLOY_CAPACITY",
    "DEPLOY_CONDITIONS",
    "DEPLOY_OK_CAPACITY",
    "LDR_ARTY_CAPACITY",
    "LDR_TNK_CAPACITY",
    "MEDIUM_EQUIP_PENALTY_CAPACITY",
    "NO_CHOC_MOVE_CAPACITY",
    "NO_SWIFT_CAPACITY",
    "SPRINT_CONDITIONS",
    "SWIFT_CAPACITY",
    "SWIFT_CONDITIONS",
]
