"""LDR capacity descriptors."""

LDR_TNK_CAPACITY = (
    'export Capacite_LDR_TNK is TCapaciteDescriptor'
    '('
    '    DescriptorId = GUID:{86360165-ed6e-4927-99fb-f4e9bb8e0b3d}'
    '    Name = "LDR_TNK"'
    '    StackPolicy = ~/CapacityStackPolicy_never'
    '    Trigger = ~/CapacityTriggerType_automatic'
    '    TargetTeamFilter = ~/CapaciteTargetFilter_joueur'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    RangeGRU = 900'
    '    CastTime = 0.00'
    '    CheckVisibility = True'
    '    CanBeCastFromTransport = False'
    '    TargetEffect = ~/UnitEffect_Instructor'
    '    CapacityDuration = -1.00'
    '    TargetInBuilding = True'
    '    TargetInTransport = False'
    '    TargetInSelf = False'
    '    TargetMySelf = False'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_soloselected | ~/CapaciteFeedbackActivationMask_allied'
    '    DisplayRangeColor = RGBA[248, 248, 248, 85]'
    '    DisplayRangeThickness = 0.20'
    '    AllowedTargetTags = ["Char_Standard", "Char_Reco", "Vehicule_Transport_Arme", "Vehicule_Reco", "Vehicule_faible", "Vehicule_Appui"]'
    '    ForbiddenTargetTags = []'
    ')'
)

LDR_ARTY_CAPACITY = (
    'export Capacite_LDR_ARTY is TCapaciteDescriptor'
    '('
    '    DescriptorId = GUID:{db0da2d1-7c98-44f4-89e4-40a7074611eb}'
    '    Name = "LDR_ARTY"'
    '    StackPolicy = ~/CapacityStackPolicy_never'
    '    Trigger = ~/CapacityTriggerType_automatic'
    '    TargetTeamFilter = ~/CapaciteTargetFilter_joueur'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    RangeGRU = 900'
    '    CastTime = 0.00'
    '    CheckVisibility = True'
    '    CanBeCastFromTransport = False'
    '    TargetEffect = ~/UnitEffect_Instructor'
    '    CapacityDuration = -1.00'
    '    TargetInBuilding = True'
    '    TargetInTransport = False'
    '    TargetInSelf = False'
    '    TargetMySelf = False'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_soloselected | ~/CapaciteFeedbackActivationMask_allied'
    '    DisplayRangeColor = RGBA[248, 248, 248, 85]'
    '    DisplayRangeThickness = 0.20'
    '    AllowedTargetTags = ["Artillerie", "Artillerie_MLRS"]'
    '    ForbiddenTargetTags = []'
    ')'
)

LDR_INF_CAPACITY = (
    'export Capacite_LDR_INF is TCapaciteDescriptor'
    '('
    '    DescriptorId = GUID:{2c3cb2e1-d4cc-412e-b798-91a2f7e6167b}'
    '    Name = "LDR_INF"'
    '    StackPolicy = ~/CapacityStackPolicy_never'
    '    Trigger = ~/CapacityTriggerType_automatic'
    '    TargetTeamFilter = ~/CapaciteTargetFilter_joueur'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    RangeGRU = 550'
    '    CastTime = 0.00'
    '    CheckVisibility = True'
    '    CanBeCastFromTransport = False'
    '    TargetEffect = ~/UnitEffect_Instructor'
    '    CapacityDuration = -1.00'
    '    TargetInBuilding = True'
    '    TargetInTransport = False'
    '    TargetInSelf = False'
    '    TargetMySelf = False'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_soloselected | ~/CapaciteFeedbackActivationMask_allied'
    '    DisplayRangeColor = RGBA[248, 248, 248, 85]'
    '    DisplayRangeThickness = 0.20'
    '    AllowedTargetTags = []'
    '    ForbiddenTargetTags = ["Canon_AA", "LDR_Unit", "LDR_SOV_Unit", "Avion", "Artillerie", "Artillerie_MLRS"]'
    ')'
)
