"""Medium equip penalty capacity."""

MEDIUM_EQUIP_PENALTY_CAPACITY = (
    'export Capacite_Medium_Equip_Penalty is TCapaciteDescriptor'
    '('
    '    DescriptorId     = GUID:{0536d4b4-7512-4519-ae59-46cf0aaef066}'
    '    Name             = "Medium_Equip_Penalty"'
    '    StackPolicy          = ~/CapacityStackPolicy_never'
    '    Trigger        = ~/CapacityTriggerType_automatic'
    '    TargetTeamFilter     = ~/CapaciteTargetFilter_joueur'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    RangeGRU            = 0'
    '    CastTime            = 5.00'
    '    CheckVisibility     = True'
    '    CanBeCastFromTransport  = True'
    '    TargetEffect         = ~/UnitEffect_Medium_Equip_Penalty'
    '    CapacityDuration   = -1.00'
    '    TargetInBuilding       = True'
    '    TargetInTransport      = True'
    '    TargetInSelf           = True'
    '    TargetMySelf           = True'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_never'
    '    DisplayRangeColor      = RGBA[0,0,0,0]'
    '    DisplayRangeThickness  = 0.00'
    '    AllowedTargetTags = []'
    '    ForbiddenTargetTags = []'
    '    Conditions = ['
    '        ~/ConditionInMovement,'
    '    ]'
    ')'
)
