"""Moving salvo reload penalty capacity."""

RELOAD_PENALTY_CAPACITY = (
    'export Capacite_Reload_Penalty is TCapaciteDescriptor'
    '('
    '    DescriptorId     = GUID:{f6a86097-01d4-4c61-9261-554fe8219f08}'
    '    Name             = "Reload_Penalty"'
    '    StackPolicy          = ~/CapacityStackPolicy_never'
    '    Trigger        = ~/CapacityTriggerType_automatic'
    '    TargetTeamFilter     = ~/CapaciteTargetFilter_joueur'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    RangeGRU            = 0'
    '    CastTime            = 0.00'
    '    CheckVisibility     = True'
    '    CanBeCastFromTransport  = False'
    '    TargetEffect         = ~/UnitEffect_Reload_Penalty'
    '    CapacityDuration       = -1.00'
    '    TargetInBuilding       = True'
    '    TargetInTransport      = False'
    '    TargetInSelf           = False'
    '    TargetMySelf           = True'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_never'
    '    DisplayRangeColor      = RGBA[0,0,0,0]'
    '    DisplayRangeThickness  = 0.00'
    '    AllowedTargetTags = []'
    '    ForbiddenTargetTags = []'
    '    Conditions = ['
    '        ~/ConditionInMovement,'
    '    ]'
    ')'
)
