"""Division UI constants."""

DIVISION_EMBLEMS = {
    "3rd_arm_small": {
        "texture_dir": r"/Assets/2D/Interface/UseOutGame/Division/Emblem",
        "texture": "3rd_arm_small.png",
    },
    "8th_inf_small": {
        "texture_dir": r"/Assets/2D/Interface/UseOutGame/Division/Emblem",
        "texture": "8th_inf_small.png",
    },
} 

GRAY_EMBLEMS = [
        "BEL_16e_Meca",
        "FR_11e_Para",
        "FR_152eID",
        "FR_5eDB",
        "Berlin_Command",
        "NL_4e_Divisie",
        "POL_20_Pc",
        "POL_4_ZMech",
        "POL_Korpus_Desantowy",
        "4_MSD_DDR",
        # "7_Panzerdivision_DDR",
        "RDA__9_Panzer",
        "RDA_KDA_Erfurt",
        "RDA_Rugen_Gruppierung",
        "2_PzGrenDivision_RFA",
        "5_Panzerdivision_RFA",
        "RFA_TerrKdo_Sud",
        # "SOV_119OdtTP",
        "SOV_25th_TD",
        # "SOV_27GvMSD",
        "35th_VDV_Brigade",
        "39th_gmsd",
        "SOV_56th_DSh_Brigade",
        "SOV_6OdtMSB",
        # "SOV_76th_VDV",
        "79th_gtd",
        "UK_1st_Armoured",
        # "UK_2nd_Infantry",
        "UK_4th_Armoured",
        "UK_5th_Airborne",
        "US_101st_Airmobile",
        "11ACR",
        "24th_infantry_division",
        "US_35th_infantry_division",
        # "3rd_Armored_Division",
        # "82nd_airborne",
        # "8th_infantry_division",
        "US_9th_Motorized",
        "WP_Unternehmen_Stoss",
        # "UK_BAOR",
    ]