"""Division matrix constants for DivisionCostMatrix.ndf"""

DIVISION_MATRICES = {
    "MatrixCostName_US_3rd_Arm_multi": (
        'MatrixCostName_US_3rd_Arm_multi is MAP'
        '['
        '    (EFactory/Art, [2, 3, 4, 5, 6]),'
        '    (EFactory/DCA, [2, 2, 4, 4, 4]),'
        '    (EFactory/Defense, [0]),'
        '    (EFactory/Helis, [2, 2, 3, 4, 5]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 3, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 4, 5, 6, 8]),'
        '    (EFactory/Recons, [2, 2, 2, 2, 3, 3, 4]),'
        '    (EFactory/Tanks, [2, 2, 2, 2, 2, 2, 3, 3]),'
        ']'
    ),

    "MatrixCostName_US_8th_Inf_multi": (
        'MatrixCostName_US_8th_Inf_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 6]),'
        '    (EFactory/DCA, [2, 2, 4, 4, 4]),'
        '    (EFactory/Defense, [0]),'
        '    (EFactory/Helis, [2, 2, 4, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 2, 3, 4, 4, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 4, 5, 6, 8]),'
        '    (EFactory/Recons, [2, 2, 2, 3, 3, 3]),'
        '    (EFactory/Tanks, [2, 2, 2, 3, 3]),'
        ']'
    ),

    "MatrixCostName_US_82nd_Airborne_multi": (
        'MatrixCostName_US_82nd_Airborne_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4]),'
        '    (EFactory/DCA, [2, 2, 3, 4, 4]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, [2, 2, 3, 4, 4, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 3, 3, 4, 6, 8]),'
        '    (EFactory/Recons, [2, 2, 2, 3, 3, 3, 3]),'
        '    (EFactory/Tanks, [2, 2, 3, 3]),'
        ']'
    ),

    "MatrixCostName_UK_2nd_Infantry_multi": (
        'MatrixCostName_UK_2nd_Infantry_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 6]),'
        '    (EFactory/DCA, [2, 2, 3, 4, 4]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, [2, 2, 3, 3, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 2, 3]),'
        '    (EFactory/Planes, [2, 2, 4, 5, 6, 8]),'
        '    (EFactory/Recons, [2, 2, 2, 3, 3, 3, 3]),'
        '    (EFactory/Tanks, [2, 2, 3, 3, 3]),'
        ']'
    ),

    "MatrixCostName_US_101st_Airmobile_multi": (
        'MatrixCostName_US_101st_Airmobile_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 2, 2, 4, 4]),'
        '    (EFactory/DCA, [2, 3, 5, 5, 5]),'
        '    (EFactory/Defense, [0, 0, 0, 0]),'
        '    (EFactory/Helis, [2, 2, 2, 3, 3, 4, 4, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 3]),'
        '    (EFactory/Planes, [2, 2, 4, 5, 6, 6]),'
        '    (EFactory/Recons, [2, 2, 2, 3, 3, 3, 3]),'
        '    (EFactory/Tanks, [4, 4, 6, 6]),'
        ']'
    ),

    "MatrixCostName_SOV_119IndTkBrig_multi": (                           
        'MatrixCostName_SOV_119IndTkBrig_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 6]),'
        '    (EFactory/DCA, [2, 2, 4, 4]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, [2, 2, 3, 4, 4, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 3, 4, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 3, 4, 5, 5, 7, 7]),'
        '    (EFactory/Recons, [2, 2, 2, 2, 3, 3, 3, 3]),'
        '    (EFactory/Tanks, [2, 2, 2, 2, 2, 3, 3, 3]),'
        ']'
    ),

    "MatrixCostName_SOV_27_Gds_Rifle_multi": (
        'MatrixCostName_SOV_27_Gds_Rifle_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 5, 6]),'
        '    (EFactory/DCA, [2, 2, 3, 3, 4, 4]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, [2, 3, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 2, 2, 3, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 2, 3, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 4, 5, 5, 7]),'
        '    (EFactory/Recons, [2, 2, 2, 4, 4, 4]),'
        '    (EFactory/Tanks, [2, 2, 3, 3, 3]),'
        ']'
    ),

    "MatrixCostName_SOV_76_VDV_multi": (
        'MatrixCostName_SOV_76_VDV_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 6]),'
        '    (EFactory/DCA, [2, 2, 3, 4, 4]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, []),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 3, 3, 4, 5, 7, 8]),'
        '    (EFactory/Recons, [2, 2, 2, 2, 2, 3, 3, 3, 3]),'
        '    (EFactory/Tanks, [2, 2, 3, 3, 3, 3]),'
        ']'
    ),

    "MatrixCostName_RDA_7_Panzer_multi": (
        'MatrixCostName_RDA_7_Panzer_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 5, 6]),'
        '    (EFactory/DCA, [2, 2, 4, 4, 6]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, [2, 2, 3, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 3, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 4, 4, 5, 7]),'
        '    (EFactory/Recons, [2, 2, 2, 2, 3, 3, 3]),'
        '    (EFactory/Tanks, [2, 2, 2, 2, 2, 2, 2, 3]),'
        ']'
    ),
    
    "MatrixCostName_RDA_KdA_Bezirk_Erfurt_multi": ( #############################
        'MatrixCostName_RDA_KdA_Bezirk_Erfurt_multi is MAP'
        '['
            '(EFactory/Art, [2, 2, 2, 4, 6, 6, 6]),'
            '(EFactory/DCA, [2, 2, 3, 4, 5]),'
            '(EFactory/Defense, []),'
            '(EFactory/Helis, [2, 2, 3, 3, 4]),'
            '(EFactory/Infantry, [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),'
            '(EFactory/Logistic, [2, 2, 2, 2, 2, 2, 2, 2, 3, 3]),'
            '(EFactory/Planes, [2, 2, 3, 4, 4, 5, 6]),'
            '(EFactory/Recons, [2, 2, 3, 4, 4]),'
            '(EFactory/Tanks, [2, 2, 3, 3, 3, 3]),'
        ']'
    ),

    "MatrixCostName_POL_20_Pancerna_multi": (
        'MatrixCostName_POL_20_Pancerna_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 5, 6]),'
        '    (EFactory/DCA, [2, 2, 4, 4, 4]),'
        '    (EFactory/Defense, [0]),'
        '    (EFactory/Helis, [2, 4, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 2, 3, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 4, 4, 5, 7]),'
        '    (EFactory/Recons, [2, 2, 2, 2, 3, 3, 3]),'
        '    (EFactory/Tanks, [2, 2, 2, 2, 2, 3, 3, 3]),'
        ']'
    ),

    "MatrixCostName_US_11ACR_multi": (
        'MatrixCostName_US_11ACR_multi is MAP'
        '['
        '    (EFactory/Art, [2, 4, 4, 6, 6]),'
        '    (EFactory/DCA, [2, 3, 4, 4, 5]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, [2, 2, 3, 3, 3, 4]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 3, 4, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 3, 4]),'
        '    (EFactory/Planes, [2, 2, 3, 4, 4, 4, 6, 6]),'
        '    (EFactory/Recons, [2, 2, 2, 2, 2, 3, 3, 3, 4]),'
        '    (EFactory/Tanks, [2, 2, 2, 3, 3, 3, 3, 3]),'
        ']'
    ),
    
    "MatrixCostName_FR_5e_Blindee_multi": (
        'MatrixCostName_FR_5e_Blindee_multi is MAP'
        '['
        '    (EFactory/Art, [2, 2, 4, 4, 4, 5]),'
        '    (EFactory/DCA, [2, 2, 3, 4, 4, 5]),'
        '    (EFactory/Defense, []),'
        '    (EFactory/Helis, [2, 3, 3, 3]),'
        '    (EFactory/Infantry, [2, 2, 2, 2, 3, 4, 4, 5]),'
        '    (EFactory/Logistic, [2, 2, 2, 2, 2, 2, 3, 3]),'
        '    (EFactory/Planes, [2, 2, 3, 5, 6, 6, 8]),'
        '    (EFactory/Recons, [2, 2, 2, 2, 3, 3, 4]),'
        '    (EFactory/Tanks, [2, 2, 2, 2, 2, 2, 3, 3]),'
        ']'
    ),
}

# old
# DIVISION_MATRICES = {
#     "MatrixCostName_US_3rd_Arm_multi": (
#         'MatrixCostName_US_3rd_Arm_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 2, 2, 3, 3]),'
#         '    (EFactory/DCA, [1, 1, 2, 2, 3]),'
#         '    (EFactory/Defense, [0]),'
#         '    (EFactory/Helis, [1, 1, 2, 2, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 2, 2, 3]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 2, 2, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 1, 1, 1, 1, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_US_8th_Inf_multi": (
#         'MatrixCostName_US_8th_Inf_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 3]),'
#         '    (EFactory/DCA, [1, 1, 2, 2, 2]),'
#         '    (EFactory/Defense, [0]),'
#         '    (EFactory/Helis, [1, 1, 2, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 2, 3, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 2, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_US_82nd_Airborne_multi": (
#         'MatrixCostName_US_82nd_Airborne_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 3]),'
#         '    (EFactory/DCA, [1, 1, 1, 2, 3]),'
#         '    (EFactory/Defense, []),'
#         '    (EFactory/Helis, [1, 1, 2, 2, 2, 2]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 1, 2, 2, 3, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_UK_2nd_Infantry_multi": (
#         'MatrixCostName_UK_2nd_Infantry_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 3]),'
#         '    (EFactory/DCA, [1, 1, 2, 2, 2]),'
#         '    (EFactory/Defense, []),'
#         '    (EFactory/Helis, [1, 2, 2, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 2, 3, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 3, 3]),'
#         '    (EFactory/Tanks, [1, 1, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_US_101st_Airmobile_multi": (
#         'MatrixCostName_US_101st_Airmobile_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/DCA, [1, 2, 3, 3, 3]),'
#         '    (EFactory/Defense, [0, 0, 0, 0]),'
#         '    (EFactory/Helis, [1, 1, 1, 2, 2, 2, 3, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]),'
#         '    (EFactory/Logistic, [1, 1, 2, 2, 3, 3, 3]),'
#         '    (EFactory/Planes, [1, 1, 2, 3, 3, 3]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 3, 3]),'
#         '    (EFactory/Tanks, [2, 2, 3, 3]),'
#         ']'
#     ),
#     "MatrixCostName_SOV_119IndTkBrig_multi": (
#         'MatrixCostName_SOV_119IndTkBrig_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 3]),'
#         '    (EFactory/DCA, [1, 1, 2, 2]),'
#         '    (EFactory/Defense, []),'
#         '    (EFactory/Helis, [1, 1, 2, 2, 2, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 2, 2, 3]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 1, 2]),'
#         '    (EFactory/Planes, [1, 1, 2, 2, 2, 3, 4, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 1, 1, 1, 2, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_SOV_27_Gds_Rifle_multi": (
#         'MatrixCostName_SOV_27_Gds_Rifle_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 2, 3]),'
#         '    (EFactory/DCA, [1, 1, 1, 2, 2, 3]),'
#         '    (EFactory/Defense, []),'
#         '    (EFactory/Helis, [1, 2, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 1, 1, 1, 2, 3]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 1, 2, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 2, 2, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 2, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_SOV_76_VDV_multi": (
#         'MatrixCostName_SOV_76_VDV_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 3]),'
#         '    (EFactory/DCA, [1, 1, 2, 2, 2]),'
#         '    (EFactory/Defense, []),'
#         '    (EFactory/Helis, []),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 1, 2, 2, 2, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 1, 2, 2, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 1, 2, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_RDA_7_Panzer_multi": (
#         'MatrixCostName_RDA_7_Panzer_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 3, 3]),'
#         '    (EFactory/DCA, [1, 1, 2, 2, 3]),'
#         '    (EFactory/Defense, []),'
#         '    (EFactory/Helis, [1, 1, 2, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 2, 2, 3]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 2, 2, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 1, 1, 1, 2, 2, 2]),'
#         ']'
#     ),
#     "MatrixCostName_POL_20_Pancerna_multi": (
#         'MatrixCostName_POL_20_Pancerna_multi is MAP'
#         '['
#         '    (EFactory/Art, [1, 1, 2, 2, 3, 3]),'
#         '    (EFactory/DCA, [1, 1, 2, 2, 3]),'
#         '    (EFactory/Defense, [0]),'
#         '    (EFactory/Helis, [1, 2, 2, 3]),'
#         '    (EFactory/Infantry, [1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Logistic, [1, 1, 1, 1, 1, 1, 1, 1, 2, 2]),'
#         '    (EFactory/Planes, [1, 1, 2, 2, 3, 4]),'
#         '    (EFactory/Recons, [1, 1, 1, 2, 2, 2, 3]),'
#         '    (EFactory/Tanks, [1, 1, 1, 1, 1, 2, 2, 2]),'
#         ']'
#     ),
# }
