"""Division matrix constants."""

DIVISION_MATRICES = {
    "MatrixCostName_US_3rd_Arm_multi": (
        'MatrixCostName_US_3rd_Arm_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 2, 2, 3, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Defense, [0]),'
        '    (EDefaultFactories/Helis, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 2, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 1, 1, 1, 1, 2, 2]),'
        ']'
    ),
    "MatrixCostName_US_8th_Inf_multi": (
        'MatrixCostName_US_8th_Inf_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 2, 2, 2]),'
        '    (EDefaultFactories/Defense, [0]),'
        '    (EDefaultFactories/Helis, [1, 1, 2, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 3, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 2, 2, 2]),'
        ']'
    ),
    "MatrixCostName_US_82nd_Airborne_multi": (
        'MatrixCostName_US_82nd_Airborne_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 1, 2, 3]),'
        '    (EDefaultFactories/Defense, []),'
        '    (EDefaultFactories/Helis, [1, 1, 2, 2, 2, 2]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 1, 2, 2, 3, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 2, 2]),'
        ']'
    ),
    "MatrixCostName_UK_2nd_Infantry_multi": (
        'MatrixCostName_UK_2nd_Infantry_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 2, 2, 2]),'
        '    (EDefaultFactories/Defense, []),'
        '    (EDefaultFactories/Helis, [1, 2, 2, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 3, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 3, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 2, 2]),'
        ']'
    ),
    "MatrixCostName_US_101st_Airmobile_multi": (
        'MatrixCostName_US_101st_Airmobile_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/DCA, [1, 2, 3, 3, 3]),'
        '    (EDefaultFactories/Defense, [0, 0, 0, 0]),'
        '    (EDefaultFactories/Helis, [1, 1, 1, 2, 2, 2, 3, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]),'
        '    (EDefaultFactories/Logistic, [1, 1, 2, 2, 3, 3, 3]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 3, 3, 3]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 3, 3]),'
        '    (EDefaultFactories/Tanks, [2, 2, 3, 3]),'
        ']'
    ),
    "MatrixCostName_SOV_119IndTkBrig_multi": (
        'MatrixCostName_SOV_119IndTkBrig_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 2, 2]),'
        '    (EDefaultFactories/Defense, []),'
        '    (EDefaultFactories/Helis, [1, 1, 2, 2, 2, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 1, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 2, 2, 3, 4, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 1, 1, 1, 2, 2, 2]),'
        ']'
    ),
    "MatrixCostName_SOV_27_Gds_Rifle_multi": (
        'MatrixCostName_SOV_27_Gds_Rifle_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 2, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Defense, []),'
        '    (EDefaultFactories/Helis, [1, 2, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 1, 1, 1, 2, 3]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 1, 2, 2, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 2, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 2, 2, 2]),'
        ']'
    ),
    "MatrixCostName_SOV_76_VDV_multi": (
        'MatrixCostName_SOV_76_VDV_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 2, 2, 2]),'
        '    (EDefaultFactories/Defense, []),'
        '    (EDefaultFactories/Helis, []),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 1, 2, 2, 2, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 1, 2, 2, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 1, 2, 2, 2]),'
        ']'
    ),
    "MatrixCostName_RDA_7_Panzer_multi": (
        'MatrixCostName_RDA_7_Panzer_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 3, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Defense, []),'
        '    (EDefaultFactories/Helis, [1, 1, 2, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 2, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 1, 1, 1, 2, 2, 2]),'
        ']'
    ),
    "MatrixCostName_POL_20_Pancerna_multi": (
        'MatrixCostName_POL_20_Pancerna_multi is MAP'
        '['
        '    (EDefaultFactories/Art, [1, 1, 2, 2, 3, 3]),'
        '    (EDefaultFactories/DCA, [1, 1, 2, 2, 3]),'
        '    (EDefaultFactories/Defense, [0]),'
        '    (EDefaultFactories/Helis, [1, 2, 2, 3]),'
        '    (EDefaultFactories/Infantry, [1, 1, 1, 1, 1, 1, 2, 2]),'
        '    (EDefaultFactories/Logistic, [1, 1, 1, 1, 1, 1, 1, 1, 1, 2]),'
        '    (EDefaultFactories/Planes, [1, 1, 2, 2, 3, 4]),'
        '    (EDefaultFactories/Recons, [1, 1, 1, 2, 2, 2, 3]),'
        '    (EDefaultFactories/Tanks, [1, 1, 1, 1, 1, 2, 2, 2]),'
        ']'
    ),
} 