"""Leader unit edits"""

from typing import Any, Dict

#fmt: off
ldr_unit_edits = {
    
    "Rifles_half_CMD_US": {
        "GameName": "#LDR FIRE TEAM LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_IFV",
                "UNITE_Rifles_half_CMD_US",
                "Unite",
            ],
        "SquadSize": 6,
        "WeaponAssignment": [
                (0,[0,]),
                (1,[0,]),
                (2,[1,]),
                (3,[1,]),
                (4,[1,3]),
                (5,[1,2]),
            ],
        "weapon1": "FM_M16",
        "weapon1_quantity": 2,
        "weapon2": "Commando_733",
        "weapon2_quantity": 4,
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                '_ifv',
                'infantry_equip_light',
            ],
        "NameToken": "CPCIJQLHML",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "RocketInf_M72A3_LAW_66mm": 6,
            },
        },
        "selector_tactic": "(0, 6)",
        "selector_tactic_obj": "00_06",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Rifles_CMD_US": {
        "GameName": "#LDR MECH. RIFLES LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "UNITE_Rifles_CMD_US",
                "Unite",
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                'infantry_equip_light',
            ],
        "NameToken": "DBEBRUEYSP",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "RocketInf_M72A3_LAW_66mm": 6,
            },
        },
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "NatGuard_CMD_US": {
        "WeaponDescriptor": {
            "equipmentchanges": {
                "replace": [("MMG_WA_M60E3_7_62mm", "MMG_M60E1_7_62mm")],
            },
        },
    },

    "Engineer_CMD_US": {
        "GameName": "#LDR ENGINEERS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_Engineer_CMD_US",
                "Unite"
            ],
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 50,
        # "SortingOrder": 20040,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                '_leader',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "WPUCULQQND",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Availability": 5,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.8],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Rangers_CMD_US": {
        "GameName": "#LDR RANGERS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "UNITE_Rangers_CMD_US",
                "Unite"
                "noSIGINT",
            ],
        "SquadSize": 9,
        "WeaponAssignment": [
                (0,[1,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,]),
                (5,[0,]),
                (6,[0,]),
                (7,[0,3]),
                (8,[0,2]),
            ],
        "weapon1": "M16A1_Carbine",
        "weapon1_quantity": 8,
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 70,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry_sf", "Texture_sf"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                '_sf',
                '_choc',
                'infantry_equip_heavy',
            ],
        "NameToken": "LRTQFDCCCB",
        "MenuIconTexture": "Texture_RTS_H_Infantry_sf",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Divisions": {
            "US_8th_Inf": {
                "Transports": ["M1038_Humvee_US", "UH60A_Black_Hawk_US"]
            },
        },
        "Availability": 4,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.75],
        "max_speed": 20,
        "WeaponDescriptor": {
            "equipmentchanges": {
                "replace": [("Commando_733", "M16A1_Carbine")],
            },
            "Salves": {
                "RocketInf_M67_RCL_90mm": 10,
            },
        },
        "unique_count": 2,
        "surrogates": 9,
        "selector_tactic": "(2, 9)",
        "selector_tactic_obj": "02_09",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Airborne_Engineer_CMD_US": {
        "GameName": "#LDR AB ENGINEERS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_Airborne_Engineer_CMD_US",
                "Unite"
            ],
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 60,
        # "SortingOrder": 20040,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                '_leader',
                '_choc',
                '_para',
                'infantry_equip_light',
            ],
        "NameToken": "JBBMCMRPWK",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Availability": 5,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.8],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Airborne_CMD_US": {
        "GameName": "#LDR AIRBORNE LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Standard",
                "UNITE_Airborne_US",
                "Unite"
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 70,
        # "SortingOrder": 20060,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                '_choc',
                '_para',
                'infantry_equip_medium',
            ],
        "NameToken": "TVWIKAOSVP",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 5,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.8],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "FM_M16": 9,
                "RocketInf_AT4_83mm": 6,
            },
        },
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "AeroRifles_CMD_US": {
        "GameName": "#LDR AERO-RIFLES LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Standard",
                "UNITE_AeroRifles_CMD_US",
                "Unite"
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 50,
        # "SortingOrder": 20060,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "MHGSSCNBFO",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 5,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.8],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Aero_half_CMD_US": {
        "GameName": "#LDR AERO-FIRE TEAM LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Standard",
                "UNITE_AeroRifles_CMD_US",
                "Unite"
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 35,
        # "SortingOrder": 20045,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 41,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "OWQFQTLBJN",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "AeroEngineer_CMD_US": {
        "GameName": "#LDR AERO-ENGINEERS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_AeroEngineer_CMD_US",
                "Unite"
            ],
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 60,
        # "SortingOrder": 20085,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 31,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                '_leader',
                '_choc',
                'infantry_equip_medium',
            ],
        "NameToken": "KFNXNJOXZS",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Availability": 4,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.75],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "GreenBerets_CMD_US": {
        "GameName": "#LDR GREEN BERETS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Standard",
                "UNITE_GreenBerets_CMD_US",
                "Unite",
                "noSIGINT",
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 75,
        # "SortingOrder": 20100,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 41,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_sf',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "ZTSGIUUUVJ",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 2,
        "XPMultiplier": [0.0, 0.0, 0.0, 1.0],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "M577_US": {
        "GameName": "#LDR M577 TACFIRE FCV",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "GroundUnits",
                "UNITE_M577_US",
                "Unite",
                "Vehicule",
            ],
        "Factory": "EDefaultFactories/Art",
        "CommandPoints": 60,
        "IdentifiedTextures": ["Texture_RTS_H_appui", "Texture_appui"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                '_leader',
            ],
        "NameToken": "CIOEKZVEAY",
        "MenuIconTexture": "Texture_RTS_H_appui",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Transport",
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 1.0, 0.0, 0.0],
    },

    "M1A1HA_Abrams_CMD_US": {
        "GameName": "#LDR M1A1(HA) ABRAMS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_M1A1HA_Abrams_CMD_US",
                "Unite",
            ],
        "CommandPoints": 335,
        # "SortingOrder": 20340,
        # "UnitAttackValue": 561,
        # "UnitDefenseValue": 561,
        "IdentifiedTextures": ["Texture_RTS_H_Armor_heavy", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'Armor_heavy',
                '_leader',
                '_smoke_launcher',
            ],
        "NameToken": "JARUASHKDH",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor_Heavy",
        "Availability": 2,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 0.0, 1.0],
    },

    "M1A1_Abrams_CMD_US": {
        "GameName": "#LDR M1A1 ABRAMS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_M1A1_Abrams_CMD_US",
                "Unite",
            ],
        "CommandPoints": 260,
        # "SortingOrder": 20290,
        # "UnitAttackValue": 461,
        # "UnitDefenseValue": 461,
        "IdentifiedTextures": ["Texture_RTS_H_Armor_heavy", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'Armor_heavy',
                '_leader',
                '_smoke_launcher',
            ],
        "NameToken": "TSLINICZXV",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor_Heavy",
        "Availability": 3,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },

    "M1IP_Abrams_CMD_US": {
        "GameName": "#LDR M1IP ABRAMS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_M1IP_Abrams_CMD_US",
                "Unite"
            ],
        "CommandPoints": 210,
        "IdentifiedTextures": ["Texture_RTS_H_Armor_heavy", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'Armor_heavy',
                '_leader',
                '_smoke_launcher',
            ],
        "NameToken": "JMIRJBBLPW",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor_Heavy",
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },

    "M1_Abrams_CMD_US": {
        "GameName": "#LDR M1 ABRAMS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_M1_Abrams_CMD_US",
                "Unite"
            ],
        "CommandPoints": 185,
        "IdentifiedTextures": ["Texture_RTS_H_Armor_heavy", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'Armor_heavy',
                '_leader',
                '_smoke_launcher',
            ],
        "NameToken": "OZPDFIGTWN",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor_Heavy",
        "Availability": 3,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },

    "M60A3_CMD_US": {
        "GameName": "#LDR M60A3 (TTS) LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_M60A3_CMD_US",
                "Unite"
            ],
        "CommandPoints": 120,
        "IdentifiedTextures": ["Texture_RTS_H_Armor", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'armor',
                '_leader',
                '_smoke_launcher',
            ],
        "NameToken": "NBZRAJWZXD",
        "MenuIconTexture": "Texture_RTS_H_Armor",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor",
        "Availability": 4,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },

    "M551A1_TTS_Sheridan_CMD_US": {
        "GameName": "#LDR M551 TTS SHERIDAN LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "M551A1_TTS_Sheridan_CMD_US",
                "Unite"
            ],
        "CommandPoints": 65,
        "IdentifiedTextures": ["Texture_RTS_H_Armor", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                '_leader',
                '_amphibie',
                '_smoke_launcher',
            ],
        "NameToken": "ZJRMUWLPVH",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor",
        "Availability": 4,
        "XPMultiplier": [0.0, 0.0, 0.0, 1.0],
    },

    "MotRifles_CMD_TTsko_SOV": {
        "GameName": "#LDRSOV MOTOSTRELKI LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_IFV",
                "UNITE_MotRifles_CMD_TTsko_SOV",
                "Unite",
            ],
        "SquadSize": 6,
        "WeaponAssignment": [
                (0,[1,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,3]),
                (5,[0,2]),
            ],
        "weapon1": "FM_AK_74",
        "weapon1_quantity": 5,
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                'leader_sov',
                '_ifv',
                'infantry_equip_light',
            ],
        "NameToken": "QCNBGTPZWL",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Divisions": {
            "SOV_27_Gds_rifle": {
                "Transports": ['GAZ_66_SOV', 'BTR_80_SOV', 'BMP_1P_SOV', 'BMP_2_SOV'],
            },
        },
        "Availability": 7,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "RocketInf_RPG22_72_5mm": 6,
            },
        },
        "selector_tactic": "(0, 6)",
        "selector_tactic_obj": "00_06",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Engineers_CMD_TTsko_SOV": {
        "GameName": "#LDRSOV SAPERI LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_Engineers_CMD_TTsko_SOV",
                "Unite"
            ],
        "SquadSize": 8,
        "WeaponAssignment": [
                (0,[0,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,]),
                (5,[0,]),
                (6,[0,]),
                (7,[0,1,]),
            ],
        "weapon1": "FM_AK_74",
        "weapon1_quantity": 8,
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 40,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                'leader_sov',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "AGYMPGDUXA",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Divisions": {
            "SOV_27_Gds_rifle": {
                "Transports": ["GAZ_66_SOV", "MTLB_transp_SOV"],
            },
        },
        "Availability": 5,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.8],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "RocketInf_RPG18_64mm": 7,
            },
        },
        "selector_tactic": "(0, 8)",
        "selector_tactic_obj": "00_08",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "Engineers_CMD_SOV": {
        "GameName": "#LDRSOV SAPERI LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_Engineers_CMD_SOV",
                "Unite"
            ],
        "SquadSize": 8,
        "WeaponAssignment": [
                (0,[0,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,]),
                (5,[0,]),
                (6,[0,]),
                (7,[0,1,]),
            ],
        "weapon1": "FM_AK_74",
        "weapon1_quantity": 8,
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 40,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                'leader_sov',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "CKLQCEBSOY",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Divisions": {
            "SOV_119IndTkBrig": {
                "Transports": ["GAZ_66_SOV", "BTR_60_SOV"],
            },
        },
        "Availability": 5,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "selector_tactic": "(0, 8)",
        "selector_tactic_obj": "00_08",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "Spetsnaz_CMD_SOV": {
        "GameName": "#LDRSOV SPETSNAZ LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_Spetsnaz_CMD_SOV",
                "Unite",
                "noSIGINT",
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry_sf", "Texture_sf"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                'leader_sov',
                '_sf',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "JSBZIJKKJJ",
        "MenuIconTexture": "Texture_RTS_H_Infantry_sf",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Divisions": {
            "SOV_119IndTkBrig": {
                "Transports": ["GAZ_66_SOV", "BTR_60_SOV"],
            },
        },
        "Availability": 4,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.75],
        "max_speed": 26,
        "selector_tactic": "(0, 8)",
        "selector_tactic_obj": "00_08",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "VDV_CMD_SOV": {
        "GameName": "#LDRSOV DESANTNIKI LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_IFV",
                "UNITE_VDV_CMD_SOV",
                "Unite",
            ],
        "SquadSize": 6,
        "WeaponAssignment": [
                (0,[1,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,3]),
                (5,[0,2,]),
            ],
        "weapon1": "PM_AKSU_74",
        "weapon1_quantity": 5,
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 50,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                'leader_sov',
                '_ifv',
                '_choc',
                '_para',
                'infantry_equip_heavy',
            ],
        "NameToken": "SWFVKVIZVT",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 5,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.8],
        "max_speed": 20,
        "WeaponDescriptor": {
            "Salves": {
                "PM_AKSU_74": 7,
                "SAW_RPK_74_5_56mm": 10,
                "MANPAD_igla": 4,
                "Grenade_SMOKE": 3,
            },
        },
        "selector_tactic": "(0, 6)",
        "selector_tactic_obj": "00_06",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Engineers_CMD_VDV_SOV": {
        "GameName": "#LDRSOV DESANT. SAPERI LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_Engineers_CMD_TTsko_SOV",
                "Unite"
            ],
        "SquadSize": 8,
        "WeaponAssignment": [
                (0,[0,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,]),
                (5,[0,]),
                (6,[0,]),
                (7,[0,1,]),
            ],
        "weapon1": "FM_AKS_74",
        "weapon1_quantity": 8,
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 50,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                'leader_sov',
                '_choc',
                '_para',
                'infantry_equip_medium',
            ],
        "NameToken": "PUEZYZBZLF",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Availability": 5,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.8],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "FM_AKS_74": 9,
                "RocketInf_RPG7": 6,
            },
        },
        "selector_tactic": "(0, 8)",
        "selector_tactic_obj": "00_08",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "MTLB_CMD_SOV": {
        "GameName": "#LDRSOV MT-LBu MASHINA",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "GroundUnits",
                "UNITE_MTLB_CMD_SOV",
                "Unite",
                "Vehicule",
            ],
        "Factory": "EDefaultFactories/Art",
        "CommandPoints": 60,
        "IdentifiedTextures": ["Texture_RTS_H_appui", "Texture_appui"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'leader_sov',
                '_amphibie',
            ],
        "NameToken": "YWAOJLFAFW",
        "MenuIconTexture": "Texture_RTS_H_appui",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Transport",
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 1.0, 0.0, 0.0],
    },

    "T80BV_CMD_SOV": {
        "GameName": "#LDRSOV T-80BVK LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_T80BV_CMD_SOV",
                "Unite",
            ],
        "armor": {
            "front": 18,
        },
        "CommandPoints": 225,
        "IdentifiedTextures": ["Texture_RTS_H_Armor_heavy", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'Armor_heavy',
                'leader_sov',
                '_smoke_launcher',
            ],
        "NameToken": "LJDWEYDMZI",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor_Heavy",
        "Availability": 4,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },

    "MotRifles_CMD_DDR": {
        "GameName": "#LDRSOV MOT.-SCHUTZEN LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_IFV",
                "UNITE_MotRifles_CMD_DDR",
                "Unite",
            ],
        "SquadSize": 6,
        "WeaponAssignment": [
                (0,[1,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,3]),
                (5,[0,2]),
            ],
        "weapon1": "FM_Mpi_AK_74N",
        "weapon1_quantity": 5,
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                'leader_sov',
                '_ifv',
                'infantry_equip_light',
            ],
        "NameToken": "KYSSUXXTDG",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "RocketInf_RPG18_64mm": 6,
            },
        },
        "selector_tactic": "(0, 6)",
        "selector_tactic_obj": "00_06",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "Engineers_CMD_DDR": {
        "GameName": "#LDRSOV PIONIER LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_Spec_Attaque",
                "UNITE_Engineers_CMD_DDR",
                "Unite"
            ],
        "SquadSize": 8,
        "WeaponAssignment": [
                (0,[0,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,]),
                (5,[0,]),
                (6,[0,]),
                (7,[0,1,]),
            ],
        "weapon1": "FM_Mpi_AK_74N",
        "weapon1_quantity": 8,
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 50,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                'leader_sov',
                '_choc',
                '_resolute',
                'infantry_equip_medium',
            ],
        "NameToken": "MXTHDKLGFB",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "FM_Mpi_AK_74N": 9,
                "RocketInf_RPG7VL": 6,
            },
        },
        "selector_tactic": "(0, 8)",
        "selector_tactic_obj": "00_08",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },

    "BTR_50_CMD_DDR": {
        "GameName": "#LDRSOV SPW-50PU(A)",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "GroundUnits",
                "UNITE_BTR_50_CMD_DDR",
                "Unite",
                "Vehicule",
            ],
        "Factory": "EDefaultFactories/Art",
        "CommandPoints": 60,
        "IdentifiedTextures": ["Texture_RTS_H_appui", "Texture_appui"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'leader_sov',
                '_amphibie',
                '_resolute',
            ],
        "NameToken": "VKLRXNSTQE",
        "MenuIconTexture": "Texture_RTS_H_appui",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Transport",
        "Availability": 2,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 1.0, 0.0, 0.0],
    },

    "T55A_CMD_DDR": {
        "GameName": "#LDRSOV FUPZ. T-55AK LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_T55A_CMD_DDR",
                "Unite",
            ],
        "CommandPoints": 85,
        "IdentifiedTextures": ["Texture_RTS_H_Armor", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'armor',
                'leader_sov',
                '_resolute',
                '_smoke_launcher',
            ],
        "NameToken": "XVEZUMJKLL",
        "MenuIconTexture": "Texture_RTS_H_Armor",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor",
        "Availability": 6,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },

    "T72M_CMD_DDR": {
        "GameName": "#LDRSOV FUPZ. T-72M LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_T72M_CMD_DDR",
                "Unite",
            ],
        "CommandPoints": 170,
        "IdentifiedTextures": ["Texture_RTS_H_Armor_heavy", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'Armor_heavy',
                'leader_sov',
                '_resolute',
                '_smoke_launcher',
            ],
        "NameToken": "QMPRIAZFYF",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor_Heavy",
        "Availability": 4,
        "cards": {
            "default": 1,
        },
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },
    
    "Territorial_CMD_UK": {
        "GameName": "#LDR TERRIERS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "UNITE_Territorial_CMD_UK",
                "Unite",
            ],
        "SquadSize": 7,
        "WeaponAssignment": [
                (0,[1,]),
                (1,[1,]),
                (2,[1,]),
                (3,[1,]),
                (4,[0,]),
                (5,[0,]),
                (6,[0,2,]),
            ],
        "weapon1": "PM_Sterling",
        "weapon1_quantity": 3,
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                'infantry_equip_light',
            ],
        "NameToken": "VZOODKAGWE",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "PM_Sterling": 12,
            },
        },
        "selector_tactic": "(0, 2)",
        "selector_tactic_obj": "00_02",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "Engineers_CMD_UK": {
        "GameName": "#LDR ASSAULT PIONEERS LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "UNITE_Engineers_CMD_UK",
                "Unite",
            ],
        "SquadSize": 8,
        "WeaponAssignment": [
                (0,[0,]),
                (1,[0,]),
                (2,[0,]),
                (3,[0,]),
                (4,[0,]),
                (5,[0,]),
                (6,[0,]),
                (7,[0,]),
            ],
        "weapon1": "PM_Sterling",
        "weapon1_quantity": 8,
        "TransportedTexture": "UseInGame_Transport_assault",
        "CommandPoints": 40,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_assault", "Texture_assault"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'engineer',
                '_leader',
                '_choc',
                'infantry_equip_light',
            ],
        "NameToken": "YGMKZKXXEV",
        "MenuIconTexture": "Texture_RTS_H_assault",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Engineer",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "WeaponDescriptor": {
            "Salves": {
                "PM_Sterling": 12,
            },
        },
        "selector_tactic": "(0, 8)",
        "selector_tactic_obj": "00_08",
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "Rifles_CMD_UK": {
        "GameName": "#LDR RIFLES LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "Infanterie_IFV",
                "UNITE_Rifles_CMD_UK",
                "Unite",
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                '_ifv',
                'infantry_equip_light',
            ],
        "NameToken": "CFLNZATSET",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "Airmobile_CMD_UK": {
        "GameName": "#LDR AIRMOBILE LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "UNITE_Airmobile_CMD_UK",
                "Unite",
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                'infantry_equip_light',
            ],
        "NameToken": "STDJMZHFVM",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "Airmobile_Mot_CMD_UK": {
        "GameName": "#LDR MOT. AIRMOBILE LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Crew",
                "GroundUnits",
                "Inf_quartier_ok",
                "Infanterie",
                "UNITE_Mot_Airmobile_CMD_UK",
                "Unite",
            ],
        "TransportedTexture": "UseInGame_Transport_REGINF",
        "CommandPoints": 40,
        # "SortingOrder": 20075,
        # "UnitAttackValue": 1,
        # "UnitDefenseValue": 16,
        "IdentifiedTextures": ["Texture_RTS_H_Infantry", "Texture_Infantry"],
        "UnidentifiedTextures": ["Texture_RTS_H_infantry_nonIdentifie", "Texture_infantry_nonIdentifie"],
        "SpecialtiesList": [
                'infantry',
                '_leader',
                'infantry_equip_light',
            ],
        "NameToken": "AXNCJBTALK",
        "MenuIconTexture": "Texture_RTS_H_Infantry",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Infantry",
        "Availability": 7,
        "XPMultiplier": [0.0, 0.0, 1.0, 0.68],
        "max_speed": 26,
        "is_infantry": True,
        "is_ground_vehicle": False,
    },
    
    "Challenger_1_Mk1_CMD_UK": {
        "GameName": "#LDR CHALLENGER MK.2 LDR.",
        "TagSet": [
                "AllUnits",
                "AllowedForMissileRoE",
                "Char",
                "GroundUnits",
                "UNITE_Challenger_1_Mk1_CMD_UK",
                "Unite"
            ],
        "CommandPoints": 205,
        "IdentifiedTextures": ["Texture_RTS_H_Armor_heavy", "Texture_Armor"],
        "UnidentifiedTextures": ["Texture_RTS_H_veh_nonIdentifie", "Texture_veh_nonIdentifie"],
        "SpecialtiesList": [
                'Armor_heavy',
                '_leader',
                '_smoke_launcher',
            ],
        "NameToken": "DPDYRJPOBS",
        "MenuIconTexture": "Texture_RTS_H_Armor_heavy",
        "TypeStrategicCount": "ETypeStrategicDetailedCount/Armor_Heavy",
        "XPMultiplier": [0.0, 0.0, 1.0, 0.0],
    },
}
#fmt: on
