"""Gameplay modification modules."""


from typing import Any, Callable, Dict, List

# New import structure
from .gameplay import (
    add_unit_meshes,
    edit_gameplay_constantes_gdconstants,
    edit_gameplay_constantes_ravitaillement,
    edit_gameplay_constantes_weaponconstantes,
    edit_gameplay_terrains,
    edit_gameplay_unit_airplanecritical,
    edit_gameplay_unit_groundunitcritical,
    edit_gameplay_unit_helicocritical,
    edit_gameplay_unit_infanteriecritical,
    edit_gameplay_unit_team,
    edit_gameplay_unit_templatecritical,
    edit_gameplay_unit_testunitscritical,
)
from .generated import (
    edit_gen_gp_decks,
    edit_gen_gp_decks_deckpacks,
    edit_gen_gp_decks_deckserializer,
    edit_gen_gp_decks_divisioncostmatrix,
    edit_gen_gp_decks_divisionrules,
    edit_gen_gp_decks_divisions,
    edit_gen_gp_decks_strategicdecks,
    edit_gen_gp_decks_strategicpacks,
    edit_gen_gp_gfx_ammunition,
    edit_gen_gp_gfx_ammunitionmissiles,
    edit_gen_gp_gfx_missiledescriptors,
    edit_gen_gp_gfx_buildingdescriptors,
    edit_gen_gp_gfx_capacitelist,
    edit_gen_gp_gfx_conditionsdescriptor,
    edit_gen_gp_gfx_damagelevels,
    edit_gen_gp_gfx_damageresistance,
    edit_gen_gp_gfx_damageresistancefamilylist,
    edit_gen_gp_gfx_damageresistancefamilylistimpl,
    edit_gen_gp_gfx_depictionaerialghosts,
    edit_gen_gp_gfx_depictionaerialunits,
    edit_gen_gp_gfx_depictionaerialunitsshowroom,
    edit_gen_gp_gfx_depictionalternatives,
    edit_gen_gp_gfx_depictionghosts,
    edit_gen_gp_gfx_depictionhumans,
    edit_gen_gp_gfx_depictioninfantry,
    edit_gen_gp_gfx_depictionvehicles,
    edit_gen_gp_gfx_depictionvehiclesshowroom,
    edit_gen_gp_gfx_effetssurunite,
    edit_gen_gp_gfx_experiencelevels,
    edit_gen_gp_gfx_firedescriptor,
    edit_gen_gp_gfx_ndfdepictionlist,
    edit_gen_gp_gfx_mimeticghosts,
    edit_gen_gp_gfx_missilecarriage,
    edit_gen_gp_gfx_missilecarriagedepiction,
    edit_gen_gp_gfx_orderavailabilitytactic,
    edit_gen_gp_gfx_smokedescriptor,
    edit_gen_gp_gfx_unitedescriptor,
    edit_gen_gp_gfx_weapondescriptor,
    edit_gen_ui_buttontexturesunites,
    edit_gen_ui_divisiontextures,
    edit_gen_ui_minimapicons,
    edit_gen_ui_specialityicontextures,
    edit_gen_ui_unitspecialties,
    edit_gen_ui_weapontextures,
    edit_gen_ui_weapontraits,
    edit_gen_ui_weaponsminmax,
)
from .userinterface import (
    edit_ui_ingame_uispecificunitinfopanelview,
    edit_ui_ingame_useingametextures,
    edit_ui_style_defaulttextformatscript,
)

__all__ = [
    # .gameplay
    'add_unit_meshes',
    'edit_gameplay_constantes_gdconstants',
    'edit_gameplay_constantes_ravitaillement',
    'edit_gameplay_constantes_weaponconstantes',
    'edit_gameplay_terrains',
    'edit_gameplay_unit_airplanecritical',
    'edit_gameplay_unit_groundunitcritical',
    'edit_gameplay_unit_helicocritical',
    'edit_gameplay_unit_infanteriecritical',
    'edit_gameplay_unit_team',
    'edit_gameplay_unit_templatecritical',
    'edit_gameplay_unit_testunitscritical',
    # .generated
    'edit_gen_gp_decks',
    'edit_gen_gp_decks_deckpacks',
    'edit_gen_gp_decks_deckserializer',
    'edit_gen_gp_decks_divisioncostmatrix',
    'edit_gen_gp_decks_divisionrules',
    'edit_gen_gp_decks_divisions',
    'edit_gen_gp_decks_strategicdecks',
    'edit_gen_gp_decks_strategicpacks',
    'edit_gen_gp_gfx_ammunition',
    'edit_gen_gp_gfx_ammunitionmissiles',
    'edit_gen_gp_gfx_missiledescriptors',
    'edit_gen_gp_gfx_buildingdescriptors',
    'edit_gen_gp_gfx_capacitelist',
    'edit_gen_gp_gfx_conditionsdescriptor',
    'edit_gen_gp_gfx_damagelevels',
    'edit_gen_gp_gfx_damageresistance',
    'edit_gen_gp_gfx_damageresistancefamilylist',
    'edit_gen_gp_gfx_damageresistancefamilylistimpl',
    'edit_gen_gp_gfx_depictionaerialghosts',
    'edit_gen_gp_gfx_depictionaerialunits',
    'edit_gen_gp_gfx_depictionaerialunitsshowroom',
    'edit_gen_gp_gfx_depictionalternatives',
    'edit_gen_gp_gfx_depictionghosts',
    'edit_gen_gp_gfx_depictionhumans',
    'edit_gen_gp_gfx_depictioninfantry',
    'edit_gen_gp_gfx_depictionvehicles',
    'edit_gen_gp_gfx_depictionvehiclesshowroom',
    'edit_gen_gp_gfx_effetssurunite',
    'edit_gen_gp_gfx_experiencelevels',
    'edit_gen_gp_gfx_firedescriptor',
    'edit_gen_gp_gfx_ndfdepictionlist',
    'edit_gen_gp_gfx_mimeticghosts',
    'edit_gen_gp_gfx_missilecarriage',
    'edit_gen_gp_gfx_missilecarriagedepiction',
    'edit_gen_gp_gfx_orderavailabilitytactic',
    'edit_gen_gp_gfx_smokedescriptor',
    'edit_gen_gp_gfx_unitedescriptor',
    'edit_gen_gp_gfx_weapondescriptor',
    'edit_gen_ui_buttontexturesunites',
    'edit_gen_ui_divisiontextures',
    'edit_gen_ui_minimapicons',
    'edit_gen_ui_specialityicontextures',
    'edit_gen_ui_unitspecialties',
    'edit_gen_ui_weapontextures',
    'edit_gen_ui_weapontraits',
    'edit_gen_ui_weaponsminmax',
    # .userinterface
    'edit_ui_ingame_uispecificunitinfopanelview',
    'edit_ui_ingame_useingametextures',
    'edit_ui_style_defaulttextformatscript',
]