"""Re-exports for unit effect descriptor fragments."""

from .medium_equip_penalty_effects import (
    MEDIUM_EQUIP_PENALTY_CAPACITY_DURATION,
    MEDIUM_EQUIP_PENALTY_COHESION_FLOOR_VALUE,
    MEDIUM_EQUIP_PENALTY_EFFECT,
    MEDIUM_EQUIP_PENALTY_FLOOR_DAMAGE_LEVEL,
    MEDIUM_EQUIP_PENALTY_FLOOR_TAG_EFFECT,
    MEDIUM_EQUIP_PENALTY_SF_EFFECT,
    MEDIUM_EQUIP_PENALTY_SF_SUPPRESS_DAMAGE,
    MEDIUM_EQUIP_PENALTY_SUPPRESS_DAMAGE,
    MEDIUM_EQUIP_PENALTY_TICK_SECONDS,
    MEDIUM_EQUIP_PENALTY_TRAIT_SUPPRESS_LINE,
)
from .deploy_effects import DEPLOY_EFFECT, DEPLOY_OK_EFFECT
from .choc_effects import CHOC_INRANGE_FEEDBACK_EFFECT, CHOC_INRANGE_TAG_EFFECT
from .sprint_effects import CHOC_SPRINT_BONUSES, NO_SPRINT_MORALE_EFFECT, SPRINT_EFFECT
from .swift_effects import NO_SWIFT_EFFECT, SWIFT_EFFECT, SWIFT_OK_EFFECT

CHOC_CQC_BONUSES = {
    "physical_damage_bonus": 15,
    "aim_time_multiplier": 0.70,
    "salvo_reload_multiplier": 0.70,
    "shot_reload_percentage": -30,
}

__all__ = [
    "CHOC_CQC_BONUSES",
    "CHOC_INRANGE_FEEDBACK_EFFECT",
    "CHOC_INRANGE_TAG_EFFECT",
    "CHOC_SPRINT_BONUSES",
    "NO_SPRINT_MORALE_EFFECT",
    "SPRINT_EFFECT",
    "MEDIUM_EQUIP_PENALTY_CAPACITY_DURATION",
    "MEDIUM_EQUIP_PENALTY_COHESION_FLOOR_VALUE",
    "MEDIUM_EQUIP_PENALTY_EFFECT",
    "MEDIUM_EQUIP_PENALTY_FLOOR_DAMAGE_LEVEL",
    "MEDIUM_EQUIP_PENALTY_FLOOR_TAG_EFFECT",
    "MEDIUM_EQUIP_PENALTY_SF_EFFECT",
    "MEDIUM_EQUIP_PENALTY_SF_SUPPRESS_DAMAGE",
    "MEDIUM_EQUIP_PENALTY_SUPPRESS_DAMAGE",
    "MEDIUM_EQUIP_PENALTY_TICK_SECONDS",
    "MEDIUM_EQUIP_PENALTY_TRAIT_SUPPRESS_LINE",
    "DEPLOY_EFFECT",
    "DEPLOY_OK_EFFECT",
    "NO_SWIFT_EFFECT",
    "SWIFT_EFFECT",
    "SWIFT_OK_EFFECT",
]
