SPRINT_EFFECT = (
    'export UnitEffect_Sprint is TEffectsPackDescriptor'
    '('
    '    DescriptorId       = GUID:{c3dbf0eb-c573-47b6-ba19-2d17ad3f9f24}'
    '    NameForDebug       = "Sprint"'
    '    EffectsDescriptors = ['
    '        TUnitEffectIncreaseDamageTakenDescriptor'
    '        ('
    '            ModifierType = ~/ModifierType_Multiplicatif'
    '            BonusDamage = 0.75'
    '            DamageType  = ~/EDamageType/Suppress'
    '        ),'
    '        TEffectInflictDamageDescriptor'
    '        ('
    '            DamageType = ~/EDamageType/Suppress'
    '            ModifierType = ~/ModifierType_Additionnel'
    '            DamageValue = 30' # Buffer to prevent suppression regeneration from instantly cancelling the effect
    '        ),'
    '        TUnitEffectIncreaseSpeedDescriptor'
    '        ('
    '            ModifierType = ~/ModifierType_Pourcentage'
    '            BonusSpeedBaseInPercent   = 70'
    '        ),'
    '        TUnitEffectShowLabelIconDescriptor'
    '        ('
    '            TextureToken = "icone_shock_move"'
    '        ),'
    '    ]'
    ')'
)

SPRINT_ACTIVATED_EFFECT = (
    'export UnitEffect_Sprint_Activated is TEffectsPackDescriptor'
    '('
    '    DescriptorId       = GUID:{f56b73a9-652a-4c23-a048-f14d838bd021}'
    '    NameForDebug       = "Sprint_Activated"'
    '    EffectsDescriptors = ['
    '        TUnitEffectRaiseTagDescriptor'
    '        ('
    '            TagListToRaise = ["SprintActivated"]'
    '        )'
    '    ]'
    ')'
)

NO_SPRINT_EFFECT = (
    'export UnitEffect_NoSprint is TEffectsPackDescriptor'
    '('
    '    DescriptorId       = GUID:{bf1daa2b-1708-4702-80ff-4c7dfd76c2d7}'
    '    NameForDebug       = "NoSprint"'
    '    EffectsDescriptors = ['
    '        TUnitEffectRaiseTagDescriptor'
    '        ('
    '            TagListToRaise = ["NoSprint"]'
    '        )'
    '    ]'
    ')'
)

NO_SPRINT_MORALE_EFFECT = (
    'export UnitEffect_NoSprint_Morale is TEffectsPackDescriptor'
    '('
    '    DescriptorId       = GUID:{d44b363a-f062-4d38-b16d-b6f78bde17c9}'
    '    NameForDebug       = "NoSprint_Morale"'
    '    EffectsDescriptors = ['
    '        TUnitEffectRaiseTagDescriptor'
    '        ('
    '            TagListToRaise = ["NoSprint_Morale"]'
    '        )'
    '    ]'
    ')'
)

SPRINT_OK_EFFECT = (
    'export UnitEffect_Sprint_ok is TEffectsPackDescriptor'
    '('
    '    DescriptorId       = GUID:{1748af97-f02d-4f04-8367-a5fb43f93f7c}'
    '    NameForDebug       = "Sprint_ok"'
    '    EffectsDescriptors = ['
    '        TUnitEffectRaiseTagDescriptor'
    '        ('
    '            TagListToRaise = ["Sprint_ok"]'
    '        )'
    '    ]'
    ')'
)