SPRINT_EFFECT = (
    'export UnitEffect_Sprint is TEffectsPackDescriptor'
    '('
    '    DescriptorId       = GUID:{c3dbf0eb-c573-47b6-ba19-2d17ad3f9f24}'
    '    NameForDebug       = "Sprint"'
    '    EffectsDescriptors = ['
    '        TUnitEffectIncreaseDamageTakenDescriptor'
    '        ('
    '            ModifierType = ~/ModifierType_Multiplicatif'
    '            BonusDamage = 0.75'
    '            DamageType  = ~/EDamageType/Suppress'
    '        ),'
    '        TEffectInflictDamageDescriptor'
    '        ('
    '            DamageType = ~/EDamageType/Suppress'
    '            ModifierType = ~/ModifierType_Additionnel'
    '            DamageValue = 20' # Buffer to prevent suppression regeneration from instantly cancelling the effect
    '        ),'
    '        TUnitEffectIncreaseSpeedDescriptor'
    '        ('
    '            ModifierType = ~/ModifierType_Pourcentage'
    '            BonusSpeedBaseInPercent   = 70'
    '        ),'
    '        TUnitEffectShowLabelIconDescriptor'
    '        ('
    '            TextureToken = "icone_shock_move"'
    '        ),'
    '    ]'
    ')'
)

NO_SPRINT_MORALE_EFFECT = (
    'export UnitEffect_NoSprint_Morale is TEffectsPackDescriptor'
    '('
    '    DescriptorId       = GUID:{d44b363a-f062-4d38-b16d-b6f78bde17c9}'
    '    NameForDebug       = "NoSprint_Morale"'
    '    EffectsDescriptors = ['
    '        TUnitEffectRaiseTagDescriptor'
    '        ('
    '            TagListToRaise = ["NoSprint_Morale"]'
    '        )'
    '    ]'
    ')'
)
