# Build configuration
build_config:
  write_dev: true          # Set to false for release builds
  target: "gameplay"       # "gameplay" or "ui_only"
  use_ui_as_base: false    # Use UI mod as base for gameplay mod

# Data configuration
data_config:
  build_database: false    # Set to true to rebuild database
  database_path: "src/data/database"  # Database location
  update_master_metadata: false  # Set to true to update master metadata after build

# Asset configuration  
asset_config:
  target_dir: "GameData"    # Target directory in mod where assets/ will be copied

directories:
  # Base game and output paths
  warno_mods: "C:/Program Files (x86)/Steam/steamapps/common/WARNO/Mods"
  base_game: "sourcemod"
  
  # UI mod paths (can be used as source for gameplay mod)
  ui_release: "test ui"
  ui_dev: "test ui dev"
  
  # Development builds
  gameplay_dev: "WARNO ACTUAL dev"
  ui_only_dev: "test ui dev"
  
  # Release builds
  gameplay_release: "WARNO ACTUAL"
  ui_only_release: "test ui"