  # Build configuration
build_config:
  write_dev: true
  target: "gameplay"
  use_ui_as_base: false

# Data configuration
data_config:
  build_database: true
  database_path: "data/database"

# Asset configuration  
asset_config:
  target_dir: "GameData"    # Target directory in mod where assets/ will be copied

directories:
  # Base game and output paths
  warno_mods: "C:/Program Files (x86)/Steam/steamapps/common/WARNO/Mods"
  base_game: "sourcemod"
  
  # UI mod paths (can be used as source for gameplay mod)
  ui_release: "test ui"
  ui_dev: "test ui dev"
  
  # Development builds
  gameplay_dev: "test gameplay dev"
  ui_only_dev: "test ui dev"
  
  # Release builds
  gameplay_release: "test gameplay"
  ui_only_release: "test ui"