# Build configuration
build_config:
  write_dev: true          # Set to false for release builds
  target: "gameplay"       # "gameplay" or "ui_only"

# Data configuration
data_config:
  build_database: false    # Set to true to rebuild database
  database_path: "src/data/database"  # Database location
  update_master_metadata: false  # Set to true to update master metadata after build

# Asset configuration  
asset_config:
  target_dir: "GameData"    # Target directory in mod where assets/ will be copied

directories:
  # Base game and output paths
  warno_mods: "C:/Program Files (x86)/Steam/steamapps/common/WARNO/Mods"
  base_game: "sourcemod"
  
  # Development builds
  gameplay_dev: "WARNO ACTUAL dev"
  ui_only_dev: "WARNO ACTUAL UI dev"
  
  # Release builds
  gameplay_release: "WARNO ACTUAL"
  ui_only_release: "WARNO ACTUAL UI"

# divisions to hide when building dev
hide_divs:
  - "BEL_16e_Mecanisee_multi"
  - "BEL_Division_Mobilisation_multi"
  - "FR_11e_Para_multi"
  - "FR_152e_Infanterie_multi"
  # - "FR_5e_Blindee_multi"
  - "NL_CLKA_multi"
  - "NATO_Garnison_Berlin_multi"
  - "NL_4e_Divisie_multi"
  # - "POL_20_Pancerna_multi"
  # - "POL_4_Zmechanizowana_multi"
  - "POL_Korpus_Desantowy_multi"
  - "RDA_4_MSD_multi"
  # - "RDA_7_Panzer_multi"
  - "RDA_9_Panzer_multi"
  # - "RDA_KdA_Bezirk_Erfurt_multi"
  - "RDA_Rugen_Gruppierung"
  # - "RFA_2_PzGrenadier_multi"
  - "RFA_5_Panzer_multi"
  # - "RFA_TerrKdo_Sud_multi"
  # - "SOV_119IndTkBrig_multi"
  - "SOV_157_Rifle_multi"
  - "SOV_25_Tank_multi"
  # - "SOV_27_Gds_Rifle_multi"
  - "SOV_35_AirAslt_Brig_multi"
  - "SOV_39_Gds_Rifle_multi"
  - "SOV_56_AirAslt_Brig_multi"
  - "SOV_6IndMSBrig_multi"
  # - "SOV_76_VDV_multi"
  - "SOV_79_Gds_Tank_multi"
  - "UK_1st_Armoured_multi"
  # - "UK_2nd_Infantry_multi"
  - "UK_4th_Armoured_multi"
  - "UK_5th_Airborne_Brigade_multi"
  - "US_101st_Airmobile_multi"
  # - "US_11ACR_multi"
  - "US_24th_Inf_multi"
  - "US_35th_Inf_multi"
  # - "US_3rd_Arm_multi"
  - "US_6th_Light_multi"
  # - "US_82nd_Airborne_multi"
  # - "US_8th_Inf_multi"
  - "US_9th_Mot_multi"
  - "WP_Unternehmen_Zentrum_multi"
  # - "UK_BAOR"