"""Effect capacity constants."""

NO_CHOC_MOVE_CAPACITY = (
    'export Capacite_no_Choc_move is TCapaciteDescriptor'
    '('
    '    DescriptorId     = GUID:{d9387c72-50d7-4781-929b-f3d08c3ea241}'
    '    Name             = "no_Choc_move"'
    '    NameToken        = "None"'
    '    CumulEffect          = ~/CapaciteCumulEffect_jamais'
    '    Declenchement        = ~/CapaciteDeclenchementType_automatique'
    '    TypeCible            = ~/CapaciteTypeCible_soi'
    '    TargetTeamFilter     = ~/CapaciteTargetFilter_joueur'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    TargetWoundedFilter  = ~/CapaciteWoundedFilterType_tout'
    '    AreaShape            = ~/CapaciteTypeCible_soi'
    '    RadiusGRU           = 1'
    '    RangeGRU            = 1'
    '    CastTime            = 0.00'
    '    Cooldown            = 0.00'
    '    CheckVisibility     = False'
    '    AllowReflexDuringCast   = True'
    '    CanBeCastFromTransport  = True'
    '    TargetEffect         = nil'
    '    TargetEffectDuration = -1.00'
    '    SelfEffect       = ~/UnitEffect_Ajoute_Tag_no_Choc_move'
    '    SelfEffectDuration   = -1.00'
    '    MaxTargetNb            = -1'
    '    MultiplyCost           = False'
    '    TargetInBuilding       = True'
    '    TargetInTransport      = True'
    '    TargetInSelf           = True'
    '    TargetMySelf           = True'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_never'
    '    DisplayRangeColor      = RGBA[0,0,0,0]'
    '    DisplayRangeThickness  = 0.00'
    '    Price = MAP[]'
    '    TagsCiblePossible = ['
    '        "GroundUnits",'
    '    ]'
    '    Conditions = ['
    '        ~/ConditionNotInMovement,'
    '    ]'
    ')'
)

CHOC_MOVE_CAPACITY = (
    'export Capacite_Choc_move is TCapaciteDescriptor'
    '('
    '    DescriptorId     = GUID:{76a483af-5f44-4ad2-a4c2-8caef5e5f828}'
    '    Name             = "Choc_move"'
    '    NameToken        = "None"'
    '    CumulEffect          = ~/CapaciteCumulEffect_jamais'
    '    Declenchement        = ~/CapaciteDeclenchementType_automatique'
    '    TypeCible            = ~/CapaciteTypeCible_unite'
    '    TargetTeamFilter     = ~/CapaciteTargetFilter_ennemi'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    TargetWoundedFilter  = ~/CapaciteWoundedFilterType_tout'
    '    AreaShape            = ~/CapaciteAreaShape_circulaire'
    '    RadiusGRU           = 875'
    '    RangeGRU            = 875'
    '    CastTime            = 1.00'
    '    Cooldown            = 30.00'
    '    CheckVisibility     = False'
    '    AllowReflexDuringCast   = True'
    '    CanBeCastFromTransport  = False'
    '    TargetEffect         = nil'
    '    TargetEffectDuration = -1.00'
    '    SelfEffect       = ~/UnitEffect_Choc_move'
    '    SelfEffectDuration   = 100.00'
    '    MaxTargetNb            = -1'
    '    MultiplyCost           = False'
    '    TargetInBuilding       = True'
    '    TargetInTransport      = True'
    '    TargetInSelf           = True'
    '    TargetMySelf           = True'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_never'
    '    DisplayRangeColor      = RGBA[0,0,0,0]'
    '    DisplayRangeThickness  = 0.00'
    '    Price = MAP[]'
    '    TagsCiblePossible = ['
    '        "GroundUnits",'
    '    ]'
    '    TagsCibleExcluded = []'
    '    Conditions = ['
    '        ~/ConditionTagNotRaisedInUnit_Panique_1,'
    '        ~/ConditionTagNotRaisedInUnit_RadioJammed_1,'
    '        ~/ConditionTagRaisedInUnit_GroundUnit_Engaged_1'
    '    ]'
    ')'
)

CHOC_MOVE_GSR_CAPACITY = (
    'export Capacite_Choc_move_GSR is TCapaciteDescriptor'
    '('
    '    DescriptorId     = GUID:{0b012c07-67cd-4691-9fc2-9b388e9eae25}'
    '    Name             = "Choc_move_GSR"'
    '    NameToken        = "None"'
    '    CumulEffect          = ~/CapaciteCumulEffect_jamais'
    '    Declenchement        = ~/CapaciteDeclenchementType_automatique'
    '    TypeCible            = ~/CapaciteTypeCible_unite'
    '    TargetTeamFilter     = ~/CapaciteTargetFilter_ennemi'
    '    InfluenceMapAlliance = ~/AllianceRelation/vide'
    '    TargetWoundedFilter  = ~/CapaciteWoundedFilterType_tout'
    '    AreaShape            = ~/CapaciteAreaShape_circulaire'
    '    RadiusGRU           = 875'
    '    RangeGRU            = 875'
    '    CastTime            = 1.00'
    '    Cooldown            = 30.00'
    '    CheckVisibility     = False'
    '    AllowReflexDuringCast   = True'
    '    CanBeCastFromTransport  = False'
    '    TargetEffect         = nil'
    '    TargetEffectDuration = -1.00'
    '    SelfEffect       = ~/UnitEffect_Choc_move_GSR'
    '    SelfEffectDuration   = 100.00'
    '    MaxTargetNb            = -1'
    '    MultiplyCost           = False'
    '    TargetInBuilding       = True'
    '    TargetInTransport      = True'
    '    TargetInSelf           = True'
    '    TargetMySelf           = True'
    '    FeedbackActivationMask = ~/CapaciteFeedbackActivationMask_never'
    '    DisplayRangeColor      = RGBA[0,0,0,0]'
    '    DisplayRangeThickness  = 0.00'
    '    Price = MAP[]'
    '    TagsCiblePossible = ['
    '        "GroundUnits",'
    '    ]'
    '    TagsCibleExcluded = []'
    '    Conditions = ['
    '        ~/ConditionTagNotRaisedInUnit_Panique_1,'
    '        ~/ConditionTagRaisedInUnit_GroundUnit_Engaged_1'
    '    ]'
    ')'
) 