"""Unit edits for depiction files."""

from .FR_depiction_edits import (
    chasseurs_cmd_fr,
    rifles_aero_cmd_fr,
    sapeurs_cmd_fr,
    scout_aero_fr,
    vab_t20_fr,
)
from .POL_depiction_edits import (
    commandos_para_cmd_pol,
    engineers_cmd_pol,
    engineers_paras_cmd_pol,
    engineers_paras_flam_pol,
    engineers_paras_pol,
    gaz_66b_supply_pol,
    manpad_strela_2m_para_pol,
    mortier_2b9_vasilek_para_pol,
    motrifles_svd_pol,
    naval_engineers_cmd_pol,
    naval_rifle_cmd_pol,
    para_cmd_pol,
    para_hmg_pol,
    para_metis_pol,
    para_pol,
    para_security_pol,
    reserve_cmd_pol,
    rifles_hmg_pol,
    scout_para_pol,
    sniper_paras_pol,
)
from .RDA_depiction_edits import (
    fallschirmjager_cmd_ddr,
    fallschirmjager_ddr,
    fallschirmjager_falseflag_cmd_ddr,
    fallschirmjager_metys_ddr,
    grenzer_flam_ddr,
    grenzer_mot_ddr,
    kda_cmd_ddr,
    luftsturmjager_cmd_ddr,
    luftsturmjager_ddr,
    luftsturmjager_metis_ddr,
    mi_24p_s8_at_ddr,
    mi_24p_s8_at2_ddr,
    mp_ddr,
    scout_fj_ddr,
    sniper_fj_ddr,
    volkspolizei_cmd_ddr,
    volkspolizei_ddr,
)
from .RFA_depiction_edits import (
    engineers_geb_rfa_rfa,
    feldgendarmerie_rfa,
    gebirgsjager_jagdkdo_rfa,
    gebirgsjager_pzf3_rfa,
    panzergrenadier_apc_rfa,
    sniper_fern_rfa,
    unimog_s_404_rfa,
)
from .SOV_depiction_edits import (
    engineers_cmd_naval_sov,
    hvyscout_sov,
    hvyscout_ttsko_sov,
    mi_8tv_gunship_sov,
    mi_24p_sov,
    mortier_2b9_vasilek_naval_sov,
    mortier_2b9_vasilek_nonpara_sov,
    mortier_2b9_vasilek_sov,
    motrifles_btr_sov,
    motrifles_btr_ttsko_sov,
    mp_sov,
    mtlb_vasilek_sov,
    naval_rifle_cmd_sov,
    sniper_spetsnaz_sov,
    vdv_afgantsy_sov,
    # su_24m_clu_sov,
    # tos1_buratino_sov,
)
from .UK_depiction_edits import (
    airmobile_mot_cmd_uk,
    bedford_mj_4t_uk,
    engineers_cmd_uk,
    guards_cmd_uk,
    pathfinders_uk,
    rifles_berlin_uk,
    rifles_gurkhas_cmd_uk,
    rmp_uk,
    rover_101fc_supply_uk,
    sniper_guards_uk,
)
from .USA_depiction_edits import (
    a7d_corsair_ii_rkt_us,
    airborne_engineers_flash_us,
    airborne_half_dragon_us,
    engineer_cmd_us,
    engineer_usmc_cmd_us,
    engineers_dragon_us,
    engineers_usmc_us,
    f4e_phantom_ii_cbu_us,
    f4e_phantom_ii_napalm_us,
    f15c_eagle_aa_us,
    f15e_strikeeagle_us,
    f16e_cbu_us,
    f16e_napalm_us,
    f111e_aardvark_napalm_us,
    f111f_aardvark_cbu_us,
    f111f_aardvark_napalm_us,
    forcerecon_usmc_us,
    groupe_at_us,
    m3a1_bradley_cfv_us,
    m3a2_bradley_cfv_us,
    m35_supply_us,
    mp_us,
    natguard_dragon_us,
    navy_seal_us,
    pathfinder_ng_us,
    ranger_us,
    rangers_cmd_us,
    rifles_half_at4_us,
    rifles_half_cav_cmd_us,
    rifles_usmc_hmg_us,
    scout_cav_us,
    scout_us,
    scout_usmc_us,
)

__all__ = [
    # FR
    "chasseurs_cmd_fr",
    "rifles_aero_cmd_fr",
    "sapeurs_cmd_fr",
    "scout_aero_fr",
    "vab_t20_fr",
    
    # POL
    "commandos_para_cmd_pol",
    "engineers_cmd_pol",
    "engineers_paras_cmd_pol",
    "engineers_paras_flam_pol",
    "engineers_paras_pol",
    "gaz_66b_supply_pol",
    "manpad_strela_2m_para_pol",
    "mortier_2b9_vasilek_para_pol",
    "motrifles_svd_pol",
    "naval_engineers_cmd_pol",
    "naval_rifle_cmd_pol",
    "para_cmd_pol",
    "para_hmg_pol",
    "para_metis_pol",
    "para_pol",
    "para_security_pol",
    "reserve_cmd_pol",
    "rifles_hmg_pol",
    "scout_para_pol",
    "sniper_paras_pol",
    
    # RDA
    "fallschirmjager_cmd_ddr",
    "fallschirmjager_ddr",
    "fallschirmjager_falseflag_cmd_ddr",
    "fallschirmjager_metys_ddr",
    "grenzer_flam_ddr",
    "grenzer_mot_ddr",
    "kda_cmd_ddr",
    "luftsturmjager_cmd_ddr",
    "luftsturmjager_ddr",
    "luftsturmjager_metis_ddr",
    "mi_24p_s8_at_ddr",
    "mi_24p_s8_at2_ddr",
    "mp_ddr",
    "scout_fj_ddr",
    "sniper_fj_ddr",
    "volkspolizei_cmd_ddr",
    "volkspolizei_ddr",
    
    # RFA
    "engineers_geb_rfa_rfa",
    "feldgendarmerie_rfa",
    "gebirgsjager_jagdkdo_rfa",
    "gebirgsjager_pzf3_rfa",
    "panzergrenadier_apc_rfa",
    "sniper_fern_rfa",
    "unimog_s_404_rfa",
    
    # SOV
    "engineers_cmd_naval_sov",
    "hvyscout_sov",
    "hvyscout_ttsko_sov",
    "mi_8tv_gunship_sov",
    "mi_24p_sov",
    "mortier_2b9_vasilek_naval_sov",
    "mortier_2b9_vasilek_nonpara_sov",
    "mortier_2b9_vasilek_sov",
    "motrifles_btr_sov",
    "motrifles_btr_ttsko_sov",
    "mp_sov",
    "mtlb_vasilek_sov",
    "naval_rifle_cmd_sov",
    "sniper_spetsnaz_sov",
    "vdv_afgantsy_sov",
    # "su_24m_clu_sov",
    # "tos1_buratino_sov",
    
    # UK
    "airmobile_mot_cmd_uk",
    "bedford_mj_4t_uk",
    "engineers_cmd_uk",
    "guards_cmd_uk",
    "pathfinders_uk",
    "rifles_berlin_uk",
    "rifles_gurkhas_cmd_uk",
    "rmp_uk",
    "rover_101fc_supply_uk",
    "sniper_guards_uk",
    
    # USA
    "a7d_corsair_ii_rkt_us",
    "airborne_engineers_flash_us",
    "airborne_half_dragon_us",
    "engineer_cmd_us",
    "engineer_usmc_cmd_us",
    "engineers_dragon_us",
    "engineers_usmc_us",
    "f4e_phantom_ii_cbu_us",
    "f4e_phantom_ii_napalm_us",
    "f15c_eagle_aa_us",
    "f15e_strikeeagle_us",
    "f16e_cbu_us",
    "f16e_napalm_us",
    "f111e_aardvark_napalm_us",
    "f111f_aardvark_cbu_us",
    "f111f_aardvark_napalm_us",
    "forcerecon_usmc_us",
    "groupe_at_us",
    "m3a1_bradley_cfv_us",
    "m3a2_bradley_cfv_us",
    "m35_supply_us",
    "mp_us",
    "natguard_dragon_us",
    "navy_seal_us",
    "pathfinder_ng_us",
    "ranger_us",
    "rangers_cmd_us",
    "rifles_half_at4_us",
    "rifles_half_cav_cmd_us",
    "rifles_usmc_hmg_us",
    "scout_cav_us",
    "scout_us",
    "scout_usmc_us",
]
