"""Weapon balance standards (data consumed by ammunition / weapon descriptor handlers).

Subpackages / modules:
- pattern: rules applied by matching NDF traits, namespaces, calibers, range members, etc.
- by_category: rules keyed by weapon category from ammo dictionaries.
"""

from .by_category import (
    A2A_STANDARDS,
    AA_ADDITIONAL_SUPPRESS_PER_LOST_PHYSICAL,
    AA_CATEGORIES,
    AA_HAGRU_STANDARDS,
    AA_SUPPRESS_BY_PHYSICAL_DAMAGE,
    BOMB_CATEGORY_WEAPON_WHITELIST,
    BOMB_STANDARDS,
    CLU_BOMB_WEAPON_NAMES,
    DCA_STANDARDS,
    MANPAD_STANDARDS,
    RatioSpec,
    SAM_STANDARDS,
    SEAD_STANDARDS,
)
from .pattern import (
    AIM_TIME_STANDARDS,
    AimTimeRule,
    CANON_HE_DAMAGE_BY_CALIBER,
    CANON_HE_DAMAGE_EXCEPTIONS,
    CLU_SOL_DAMAGE_FAMILY_TO_TRAIT,
    CLU_SOL_TRAIT_TOKEN_CLUSTER,
    CLU_SOL_TRAIT_TOKEN_HEAT,
    HE_BOMB_DAMAGE_BY_WEIGHT,
    HE_BOMB_NAME_MATCH,
    HE_BOMB_TRAIT_TOKENS,
    WEAPON_RANGE_MEMBERS_TO_CHECK,
)

__all__ = [
    "A2A_STANDARDS",
    "AA_ADDITIONAL_SUPPRESS_PER_LOST_PHYSICAL",
    "AA_CATEGORIES",
    "AA_HAGRU_STANDARDS",
    "AA_SUPPRESS_BY_PHYSICAL_DAMAGE",
    "AIM_TIME_STANDARDS",
    "AimTimeRule",
    "BOMB_CATEGORY_WEAPON_WHITELIST",
    "BOMB_STANDARDS",
    "CLU_BOMB_WEAPON_NAMES",
    "DCA_STANDARDS",
    "MANPAD_STANDARDS",
    "RatioSpec",
    "SAM_STANDARDS",
    "SEAD_STANDARDS",
    "CANON_HE_DAMAGE_BY_CALIBER",
    "CANON_HE_DAMAGE_EXCEPTIONS",
    "HE_BOMB_DAMAGE_BY_WEIGHT",
    "HE_BOMB_NAME_MATCH",
    "HE_BOMB_TRAIT_TOKENS",
    "CLU_SOL_DAMAGE_FAMILY_TO_TRAIT",
    "CLU_SOL_TRAIT_TOKEN_CLUSTER",
    "CLU_SOL_TRAIT_TOKEN_HEAT",
    "WEAPON_RANGE_MEMBERS_TO_CHECK",
]
